name: Build Vue
on:
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'mauodias'
        reponame: 'jugglebird'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        cname: 'jugglebird.mauricio.cc'
        gitemail: ${{ github.event.pusher.email }}
        gitname: ${{ github.event.pusher.name }}