name: Build Vue
on:
  push:
    branches:
      - main
jobs:
  build_vue:
    defaults:
      run:
        working-directory: ./jugglebird
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
    - name: Build-Vue
      run: |
        npm install
        npm run build
    - name: Prepare file tree
      run: |
        mv dist ../../
        cd ..
        rm -rf *
        mv ../dist/* .
    - name: Commit files to gh-pages branch
      run: |
        git add -A
        git commit -m "Update gh-pages"
        git push -u origin gh-pages