name: Build Vue
on:
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build-Vue
      working-directory: ./jugglebird
      run: |
        npm install
        npm run build
        mv dist /tmp
    - name: Checkout gh-pages branch
      users: actions/checkout@v2
      with:
        ref: 'gh-pages'
    - name: Prepare file tree
      run: |
        rm -rf *
        mv /tmp/dist/* .
    - name: Commit files to gh-pages branch
      run: |
        git add -A
        git commit -m "Update gh-pages"
        git push -u origin gh-pages